version: "3.9"
services:
  server:
    build: .
    volumes:
      - .:/workspace
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app
      - FLASK_RUN_PORT=80
    ports:
      - "8080:80"
  redis:
    image: redis
    